project_id = "jeysistgdajopfruqpbc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.send-portal-email]
    verify_jwt = false
