-- Píldoras v2 (09-09-2026): contenido ampliado a ~8 min de lectura + recursos descargables
-- enlazados dentro de la propia píldora. Sustituye {0,content} y {0,downloadable_resources}
-- del único módulo de cada curso fp-pildora-*. Los quiz (course_quizzes) no se tocan.
-- Idempotente: volver a ejecutarlo deja el mismo resultado. Guardas: 1 módulo y id esperado.
-- Origen: contenido/v2/pildora-0N-*.md (generado con md2sql.py). NO ejecutar sin confirmación de Francesc.
BEGIN;

WITH mapeo(slug, mod_id, content, recursos) AS (VALUES
  ('fp-pildora-farmacia-silenciosa', 'fp-pildora-farmacia-silenciosa-l1', $c$
<blockquote><p>Píldora de onboarding: completar esta lección y su quiz desbloquea el primer cajón de la Rebotica.</p></blockquote>
<h3>El problema</h3>
<p>Todos los días entran clientes en tu farmacia que se van sin comprar todo lo que necesitaban. No es porque tu equipo no quiera atenderles bien: es porque ni tú ni ellos detectáis la señal a tiempo. Según el Observatorio de la Farmacia Española, el 68% de los clientes que entran en una farmacia tiene una necesidad adicional a la que expresa al llegar al mostrador, y solo un 32% de esas necesidades termina convirtiéndose en venta. Traducido a tu día a día: de cada diez personas con una segunda necesidad (una crema después de comprar el jarabe, un producto de higiene íntima después de la consulta, un complemento después de la vacuna de la gripe), siete se van sin que nadie se lo haya ofrecido.</p>
<p>Se nota en la caja al final de mes, cuando el número de tickets no acompaña al ajetreo que has visto en el mostrador durante el día. Se nota en la sensación de estar "muy liados" sin que eso se traduzca en facturación. Y se nota, sobre todo, en que no hay ningún incidente que señalar: no ha habido una queja, no ha habido un cliente enfadado, no ha habido un error de dispensación. Todo ha ido "bien". Por eso a este fenómeno lo llamamos la farmacia silenciosa: pierde oportunidades sin hacer ruido, sin que aparezca en ningún parte de incidencias, sin que nadie del equipo se dé cuenta de que ha pasado.</p>
<p>El coste real no es solo el ticket que no se cerró esa vez. Es la repetición: la misma señal (el mostrador que actúa de barrera, el auxiliar con la vista en la pantalla, la balda sin cartel) se repite con cada cliente que entra, día tras día, durante meses. Un fallo puntual se corrige solo; un patrón silencioso se instala y acaba pareciendo normal.</p>
<h3>Por qué pasa</h3>
<p>No es un problema de actitud ni de falta de ganas de tu equipo. Pasa porque estas cinco señales son invisibles desde dentro: cuando llevas años trabajando en el mismo mostrador, con el mismo diseño y las mismas rutinas, dejas de verlas. Es el mismo motivo por el que no notas el ruido de fondo de un electrodoméstico hasta que alguien de fuera te lo señala.</p>
<p>Además, ninguna de las cinco causa un problema por sí sola, y eso las hace más difíciles de detectar. El mostrador lleva ahí veinte años y nunca ha dado ningún problema. El auxiliar solo estaba terminando un pedido, no ignorando a nadie a propósito. La señalización se hizo cuando abristeis y siempre ha estado así. Cada elemento tiene una explicación razonable por separado. El problema es que los cinco funcionan a la vez, todos los días, sobre todos los clientes que cruzan la puerta, y ese efecto acumulado es el que se lleva las ventas.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. El mostrador barrera</strong></p>
<p>Fíjate en si tu mostrador invita a acercarse o si funciona como una frontera física entre el equipo y quien entra. Un mostrador alto, con el ordenador o la impresora de recetas justo entre el auxiliar y el cliente, empuja a la conversación mínima: se despacha lo que se pide y poco más. Los espacios más abiertos, donde el cliente ve al equipo de cuerpo entero y no solo la cabeza asomando por encima de una pantalla, facilitan que se anime a comentar esa segunda necesidad que no tenía pensado mencionar al entrar.</p>
<p>No hace falta una reforma para corregirlo: a veces basta con retirar de encima del mostrador lo que no es imprescindible (carteles, expositores, el propio monitor si se puede reorientar) para que el cliente vea una cara y no una pantalla. El error que más se repite aquí es pensar que el problema es "el mueble" y esperar a una reforma que nunca llega, cuando buena parte del efecto barrera se resuelve con lo que hay encima de él, no con el mostrador en sí.</p>
<p><strong>Paso 2. El personal "ocupado"</strong></p>
<p>Cuando un cliente ve a tu equipo enfrascado en una tarea administrativa, un pedido o una conversación interna, interpreta que va a molestar si pregunta. No hace falta que nadie le diga nada: la propia escena ya transmite el mensaje. El resultado es que se calla la pregunta que traía y sale con solo lo que fue a buscar.</p>
<p>En una farmacia real esto se traduce en momentos muy concretos: la hora de repasar el pedido del mayorista, el rato después de comer en el que se cuadra caja, el momento en que dos compañeros están comentando una incidencia con un paciente anterior. Ninguno de esos tres momentos es un error de gestión, pero si coinciden con la entrada de un cliente nuevo, ese cliente ya ha decidido no preguntar. El error más frecuente es asumir que "si necesita algo, ya preguntará": la experiencia de mostrador demuestra justo lo contrario, que la mayoría prefiere no interrumpir antes que sentirse inoportuna.</p>
<p><strong>Paso 3. El lenguaje corporal</strong></p>
<p>Brazos cruzados, mirada fija en el ordenador, postura rígida detrás del mostrador: son señales de "no me molestes" que el equipo transmite sin decir una palabra ni ser consciente de ello. Buena parte de lo que un cliente interpreta al entrar no viene de lo que se le dice, sino de cómo está colocado el cuerpo de quien le va a atender.</p>
<p>Es fácil de comprobar y fácil de corregir: pide a alguien de fuera del equipo que observe cómo se coloca tu gente cuando no atiende a nadie, o dedica tú diez minutos a mirarlo desde la puerta. El error habitual es pensar que esto solo importa "durante la atención": en realidad, la postura del equipo en los segundos antes de que entre el cliente es la que decide si esa persona se acerca o pasa de largo hacia la estantería más cercana.</p>
<p><strong>Paso 4. La señalización</strong></p>
<p>Si tu cliente tiene que preguntar dónde está cada cosa, muchos van a preferir no preguntar y, sencillamente, no comprar. Más de la mitad de los consumidores prefiere orientarse solo antes de pedir ayuda, así que una farmacia sin carteles claros no está siendo "discreta": está perdiendo ventas que ni siquiera llegan a formularse en voz alta.</p>
<p>En la práctica esto significa revisar zona por zona: ¿se ve desde la puerta dónde está la dermocosmética? ¿Hay un cartel que diga "higiene bucal" o solo lo sabe quien lleva diez años trabajando ahí? El ejemplo más habitual es la sección de complementos o de dermocosmética: la que más rota cuando se encuentra, pero la que menos se explora si no hay ningún indicio visual de que existe. El error más repetido es diseñar la señalización pensando en el equipo, que ya conoce la farmacia de memoria, y no en quien entra por primera vez.</p>
<p><strong>Paso 5. Los tiempos muertos</strong></p>
<p>Cada momento de espera pasiva (mientras se busca un producto en el almacén, mientras se procesa un pago, mientras se imprime un justificante) es una oportunidad de conversación que se está desperdiciando en silencio. El cliente se queda ahí parado, sin nada que hacer, y esos segundos podrían usarse para preguntar cómo le ha ido con el tratamiento anterior o si necesita algo más.</p>
<p>Un ejemplo típico: la espera en caja mientras se cobra una receta múltiple. En vez de un silencio incómodo, ese es el momento perfecto para una pregunta abierta, del tipo "¿qué tal le ha ido con la crema que se llevó la semana pasada?". El error que casi todas las farmacias cometen es tratar esos segundos como tiempo perdido que hay que acortar como sea, cuando en realidad es tiempo que hay que llenar de conversación, no de silencio.</p>
<h3>Errores frecuentes</h3>
<ul>
<li>Pensar que el problema es un mueble o una reforma pendiente, cuando casi siempre está en lo que hay encima del mostrador o en cómo se usa, no en el mostrador en sí.</li>
<li>Dar por hecho que un cliente con una necesidad adicional "ya preguntará": la experiencia de mostrador demuestra justo lo contrario, que prefiere callarse antes que sentirse inoportuno.</li>
<li>Diseñar la señalización pensando en quien lleva años trabajando en la farmacia, que ya se la sabe de memoria, y no en quien entra por primera vez.</li>
<li>Tratar los tiempos de espera como algo que solo hay que acortar, en vez de como un momento que se puede llenar de conversación.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Coge un papel y, durante la próxima hora de apertura, cronometra a los primeros cinco clientes que entren: cuánto tarda tu equipo en darles la primera señal de atención, ya sea un saludo o un simple contacto visual. El estándar de referencia es menos de 20 segundos para ese primer contacto. Apunta los tiempos exactos, con el nombre de quien atendió si quieres afinar más adelante. No corrijas nada todavía: este primer cronómetro es solo tu dato de partida, la foto real de cómo suena (o calla) tu farmacia hoy, antes de tocar nada.</p>
<h3>Cómo saber que funciona</h3>
<p>Dale 30 días al cambio antes de sacar conclusiones y mira estas tres señales:</p>
<ul>
<li>El tiempo del primer contacto baja de forma sostenida hacia los 20 segundos, no solo el día que lo mides tú delante del equipo.</li>
<li>El número de ventas cruzadas por ticket (algo tan simple como preguntar "¿algo más?" y anotar cuántas veces la respuesta es que sí) empieza a subir semana a semana.</li>
<li>Tu equipo empieza a comentar espontáneamente casos de clientes a los que "les ha pillado" una necesidad que no traían pensada: es la señal de que la escucha activa se ha instalado, no solo el cronómetro del primer día.</li>
</ul>
<h3>Para seguir</h3>
<p>Para poner cifras a las cinco señales en tu propia farmacia, tienes justo debajo, en "Recursos descargables", el checklist «10 señales de alarma en tu farmacia» en PDF: repásalo con tu equipo esta semana y usadlo como base de la auditoría silenciosa que hemos descrito en esta píldora.</p>
$c$, $r$[{"title": "Checklist: 10 señales de alarma en tu farmacia", "url": "/recursos/impulso-n01-senales-alarma.pdf", "type": "pdf", "resource_id": "3503ea74-86a0-4fcf-8dc8-ac4a68910b24"}]$r$::jsonb),
  ('fp-pildora-google-my-business', 'fp-pildora-google-my-business-l1', $c$
<h3>El problema</h3>
<p>Cuando alguien busca "farmacia cerca" o "farmacia" más el nombre de tu barrio, la decisión se toma en el móvil, de pie, en segundos. Nadie abre cinco fichas y las compara con calma: mira el mapa, las estrellas, si el horario dice "abierto ahora", y elige. Según nuestro análisis de más de 300 perfiles de farmacia en Google, la mayoría de estas búsquedas locales terminan en una visita física a una de las farmacias que aparecen en los primeros resultados (estimación sectorial). Eso significa que tu ficha de Google Business Profile, la que Google creó por su cuenta el día que abriste o incluso antes, está haciendo hoy el trabajo de un escaparate que probablemente nunca has revisado.</p>
<p>En el día a día esto se nota en cosas pequeñas que rara vez se atribuyen a Google: llamadas repetidas preguntando si estáis abiertos un festivo ya actualizado en la puerta pero no en la ficha, clientes que preguntan por un servicio que ofrecéis pero que no aparece en ningún sitio digital, o simplemente menos gente nueva de la que debería llegar dado el tráfico de tu zona. No es un fallo dramático ni visible de un día para otro: es una fuga lenta de clientes que nunca llegan a saber que existes porque la farmacia de al lado tiene tres fotos más, dos reseñas más y el horario bien puesto.</p>
<p>El coste real no es solo el cliente que se va a la competencia esa vez: cada búsqueda perdida se repite, y la próxima vez esa persona volverá a encontrar primero al vecino mejor posicionado. Con el tiempo, una ficha descuidada no solo pierde visitas puntuales, construye el hábito de que la gente de tu zona vaya primero a otro sitio. Y ocurre con una herramienta gratuita, lo que hace más llamativo que se quede a medio hacer.</p>
<h3>Por qué pasa</h3>
<p>No es pereza ni desinterés por el negocio. La ficha de Google Business Profile no se parece a nada que un titular haya gestionado antes: no es el escaparate físico, que se corrige a simple vista, ni un trámite con el Colegio o con sanidad, con fecha límite y consecuencia clara si se ignora. Es un perfil que Google generó solo, que nadie reclamó formalmente al abrir la farmacia y que sigue funcionando de fondo aunque nadie entre a revisarlo. Cuando algo funciona sin que lo toques, es fácil asumir que está bien.</p>
<p>A eso se suma que el día a día deja poco margen para lo que no es urgente. Actualizar un horario en Google nunca parece tan prioritario como atender el mostrador, y al no haber una persona del equipo con esa tarea asignada, termina sin ser de nadie. El resultado es un perfil completado a medias hace años que desde entonces solo ha acumulado desajustes: un horario de verano que nunca se quitó, un teléfono antiguo, cero fotos nuevas desde la apertura.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Verifica y actualiza lo básico</strong></p>
<p>Entra en tu ficha y compara, dato por dato, lo que dice Google con la realidad de hoy: nombre exacto (sin palabras clave metidas con calzador), dirección coherente con la de tu web o el Colegio, teléfono directo (no una centralita que nadie coge) y horario completo, con festivos y guardias incluidos. Es lo primero que ve cualquiera que busque, y lo primero que genera desconfianza si está mal.</p>
<p>En la práctica basta con revisar la ficha cada vez que cambias algo similar en otro sitio: el cartel de la puerta, el contestador, el calendario de guardias. Pedro S., titular en Alicante, lo resume bien: tras actualizar horarios y guardias, notó un descenso claro en las llamadas preguntando si estaban abiertos. Diez minutos que ahorran tiempo de mostrador y de teléfono todos los días.</p>
<p>El error que más se repite es dejar un horario especial de una temporada anterior (fiestas de hace dos años, un verano ya pasado) sin quitar, contradiciendo el horario normal y confundiendo a quien busca justo un día señalado.</p>
<p><strong>Paso 2. Completa los atributos específicos de farmacia</strong></p>
<p>Google tiene una lista de atributos pensados para negocios como el tuyo: servicios (formulación magistral, asesoramiento nutricional, consultas online, recogida en tienda), accesibilidad (rampa, espacio para sillas de ruedas) y métodos de pago. La mayoría de farmacias los deja sin marcar, como si no existieran.</p>
<p>Entra en el panel de gestión (business.google.com), busca la sección de atributos y revísalos uno a uno: cada uno describe algo concreto que probablemente ya ofreces pero nunca has declarado. Según nuestros datos, las farmacias que completan al menos 10 atributos reciben más interacciones que las que dejan la sección casi vacía.</p>
<p>El error habitual es asumir que Google "ya sabe" qué servicios ofreces por ser farmacia. No lo sabe: si no marcas que haces formulación magistral o que aceptas tarjeta, ese servicio no existe para quien busca.</p>
<p><strong>Paso 3. Activa un sistema sencillo para pedir reseñas</strong></p>
<p>El 92% de la gente lee las reseñas antes de visitar un negocio, y sin embargo la mayoría de farmacias tiene muy pocas: es justo lo que un cliente potencial compara antes de elegir. La solución no es perseguir a nadie, es reducir la fricción: un cartel en el mostrador o una tarjeta con código QR directo al formulario de reseña, entregada al cliente satisfecho en el momento justo (al recoger una fórmula, tras un buen consejo).</p>
<p>María L., titular en Barcelona, montó exactamente este sistema: identificaba a clientes satisfechos y les daba una tarjeta con QR directo a su perfil. En tres meses pasó de 6 a 47 reseñas y su valoración media subió de 3,8 a 4,7, sin cambiar nada del servicio, solo facilitando que quien ya estaba contento lo dijera en público.</p>
<p>El error más común es esperar a que las reseñas lleguen solas, lo que en la práctica significa que solo escriben los clientes enfadados. El segundo, casi tan extendido, es no responder nunca a las negativas: dejarlas sin respuesta transmite que a la farmacia no le importa.</p>
<p><strong>Paso 4. Sube fotos reales de tu farmacia</strong></p>
<p>Las imágenes transmiten confianza antes incluso de leer una palabra: fachada y entrada, interior mostrando amplitud y orden, el equipo trabajando, algún servicio especial. Sube entre 5 y 8 fotos como mínimo, nada de imágenes de stock que podrían ser de cualquier farmacia del país.</p>
<p>No hace falta una sesión profesional: basta el móvil, luz natural (antes de abrir o en un momento tranquilo) y encuadres sencillos. Según nuestros datos, las farmacias con 8 o más fotos de calidad reciben bastantes más visitas que las que tienen dos o ninguna: es la diferencia entre reconocer tu fachada al llegar o dudar si te has equivocado de portal.</p>
<p>El error típico es subir fotos una vez, en la apertura, y no tocarlas más aunque la farmacia haya cambiado de imagen o renovado el mostrador. Unas fotos de hace ocho años desentonan con la farmacia real.</p>
<p><strong>Paso 5. Publica un post semanal</strong></p>
<p>La función de publicaciones de Google es gratuita y casi nadie la usa: según nuestros datos, apenas un 7% de las farmacias españolas la aprovecha con regularidad. Un post puede anunciar una promoción, un servicio nuevo, un producto de temporada o un consejo general de salud, sin prometer resultados clínicos concretos.</p>
<p>Funciona mejor si una sola persona del equipo lo asume como tarea fija semanal: diez minutos, un mismo día, dos frases, una foto y publicar. Mantener esa frecuencia es lo que marca la diferencia frente a publicar una vez y olvidarlo.</p>
<p>El error más frecuente, aparte de abandonar la costumbre a las dos semanas, es cruzar la línea deontológica: prometer que un producto "cura" algo, o recomendar un medicamento concreto en público. Un consejo general (hidratación en verano, prevención de resfriados) sí funciona; una promesa clínica, no.</p>
<h3>Errores frecuentes</h3>
<ul>
<li><strong>Información distinta según dónde se busque:</strong> el nombre o la dirección de la ficha de Google no coincide con la de tu web o tu perfil en otros directorios. Corrígelo unificando siempre los mismos datos exactos en todas partes.</li>
<li><strong>Nadie responsable del perfil:</strong> la ficha lleva meses o años sin que nadie del equipo la revise porque no está asignada a nadie en concreto. Corrígelo nombrando a una persona (puedes rotarlo) con esa tarea fija cada mes.</li>
<li><strong>Responder solo a lo negativo, o no responder a nada:</strong> dejar reseñas negativas sin respuesta o ignorar también las positivas. Corrígelo respondiendo a todas, en pocas líneas, agradeciendo o explicando con calma lo ocurrido.</li>
<li><strong>Tratar la ficha como algo que se hace una vez:</strong> completarla al abrir la farmacia y no volver a tocarla. Corrígelo con una revisión mensual breve, la misma que verás en el siguiente apartado.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Entra en tu perfil de Google Business Profile (business.google.com) y revisa solo tres datos: horario actual (incluidos festivos próximos), teléfono directo y categoría principal. Corrige lo que esté mal. Es la acción con mejor relación esfuerzo-resultado de todo el marketing digital de una farmacia.</p>
<h3>Cómo saber que funciona</h3>
<p>Dale a esto 30 días y mira tres señales, todas visibles desde el propio panel de estadísticas de tu ficha (business.google.com, apartado de "Rendimiento"):</p>
<ul>
<li><strong>Menos llamadas preguntando si estáis abiertos.</strong> Si el horario está bien puesto, esas llamadas bajan de forma perceptible en el mostrador y en el teléfono.</li>
<li><strong>Más reseñas y mejor valoración media.</strong> No hace falta un salto como el de María L. en el primer mes, pero deberías ver reseñas nuevas entrando cada semana si el sistema de QR o tarjeta está activo.</li>
<li><strong>Más acciones en el panel de estadísticas.</strong> Google desglosa mensualmente cuánta gente pidió indicaciones para llegar, llamó desde la ficha o visitó tu web. Un aumento en cualquiera de estas tres cifras respecto al mes anterior confirma que el perfil está trabajando para ti.</li>
</ul>
<h3>Para seguir</h3>
<p>Para llevar esto más allá de los 5 pasos, tienes el descargable «Posicionamiento local paso a paso» (PDF) justo debajo, en "Recursos descargables": la guía completa para verificar y optimizar tu ficha con más detalle del que cabe en esta píldora.</p>
$c$, $r$[{"title": "Posicionamiento local paso a paso", "url": "/recursos/impulso-n06-posicionamiento-local.pdf", "type": "pdf", "resource_id": "34b109b7-47d7-4740-89c3-efeecc58ef6e"}]$r$::jsonb),
  ('fp-pildora-stock-muerto', 'fp-pildora-stock-muerto-l1', $c$
<h3>El problema</h3>
<p>Dedicas horas cada semana a negociar condiciones con los proveedores, a mirar promociones y a organizar los turnos del equipo. Pero, ¿cuánto tiempo dedicas a gestionar lo que ya has comprado? Según el Observatorio de la Distribución Farmacéutica, el 82% de las farmacias españolas tiene entre el 18% y el 26% de su stock en situación de baja o nula rotación. En una farmacia con 150.000 euros de inventario, eso son entre 27.000 y 39.000 euros parados en las estanterías: no generan ni una venta, pero sí ocupan espacio y aprietan la caja a final de mes.</p>
<p>Cuando se habla de stock muerto, lo primero que viene a la cabeza son los caducados. Es solo la punta del problema. Debajo hay un coste financiero (el capital inmovilizado tiene un coste de oportunidad, estimación sectorial entre el 7% y el 12% anual, porque ese dinero podría estar generando margen en otro sitio), un coste de espacio (el metro cuadrado de mostrador y trastienda es de lo más caro que tienes, y cada caja que no se mueve ocupa el hueco de una que sí lo haría) y un coste operativo (más referencias significan más tiempo contando, más errores de dispensación y más complejidad cada vez que haces inventario).</p>
<p>En el día a día se nota de formas muy concretas: pides una transferencia a la farmacia de al lado para cubrir una falta mientras tu propio almacén está lleno de otra cosa que no sale; tienes semanas de tesorería holgada seguidas de otras muy justas sin motivo aparente; y si alguien te preguntase ahora mismo qué referencias llevan tres meses sin moverse, no sabrías responder sin mirar el programa. Ese desconocimiento es la parte más cara del problema, porque lo que no se mide no se corrige.</p>
<h3>Por qué pasa</h3>
<p>No es un problema de mala gestión ni de falta de esfuerzo. Es un problema de sistema. La vocación sanitaria empuja a tener "de todo para todos", por si acaso lo pide un paciente, y esa mentalidad es humanamente comprensible pero empresarialmente cara. A eso se suman las ofertas por volumen de los proveedores, que a corto plazo parecen una ventaja y a medio plazo dejan un pasillo entero de un producto que rota una vez al trimestre.</p>
<p>El otro motivo es que casi ninguna farmacia tiene un sistema de alerta temprana que avise cuándo un producto está entrando en zona de riesgo. Sin ese sistema, las decisiones de compra se toman por percepción ("esto se vende mucho") en vez de por datos reales del programa de gestión, y la percepción falla más de lo que crees.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Clasifica en tres zonas: verde, amarilla y roja</strong></p>
<p>El punto de partida es un semáforo aplicado a tu inventario. La zona verde es tu motor económico: representa, como estimación sectorial, alrededor del 20% de tus referencias, pero genera el 80% de tus ventas. La zona amarilla ronda el 30% de referencias y el 15% de ventas. Y la zona roja concentra hasta el 50% de tus referencias con apenas el 5% de las ventas: ahí está el verdadero problema.</p>
<p>Para hacerlo en tu farmacia, saca del programa de gestión el listado de unidades vendidas por referencia en los últimos doce meses, ordénalo de mayor a menor y marca los tres tramos. No hace falta que sea exacto al decimal: con clasificar de forma aproximada ya tienes una foto que antes no tenías. En una farmacia de tamaño medio, con dos o tres mil referencias, es habitual encontrar mil o más en zona roja la primera vez que se hace este ejercicio.</p>
<p>El error más repetido aquí es clasificar de oído, por la impresión que tienes de cada producto, en lugar de mirar el dato del programa. La memoria del titular es selectiva: recuerda lo que se vendió bien la semana pasada y olvida lo que lleva un año quieto en la balda de arriba.</p>
<p><strong>Paso 2. Dentro de la roja, separa estratégicos, en declive y "error"</strong></p>
<p>No todo lo que está en rojo se trata igual. Hay productos estratégicos que necesitas tener aunque roten poco, por ejemplo un antiparasitario concreto que un paciente pide de vez en cuando: si no lo tienes, pierdes esa venta y probablemente al paciente. Hay productos en declive, que antes rotaban bien y han ido perdiendo fuelle, normalmente porque cambió la demanda o apareció una alternativa. Y hay productos "error": los que compraste por una oferta que parecía buena y que, sencillamente, nunca funcionaron en tu mostrador.</p>
<p>A estos tres grupos se suman los estacionales fuera de temporada, que no son stock muerto real sino stock dormido: solares en noviembre, por ejemplo.</p>
<p>El error frecuente en este paso es tratar toda la zona roja como si fuera un único bloque a liquidar. Eso te lleva a deshacerte también de los productos estratégicos que sí necesitas mantener, y a las pocas semanas te faltan cuando un paciente los pide.</p>
<p><strong>Paso 3. Fija un punto de pedido por zona</strong></p>
<p>Cada zona necesita una regla de reposición distinta. En la zona verde, la prioridad es que nunca falte: revisa con frecuencia las condiciones comerciales porque es tu volumen de negociación real. En la zona amarilla, haz una revisión mensual y ajusta el punto de pedido según la estacionalidad. En la zona roja, la regla es la contraria: no repongas sin revisión previa. Deja que el producto se agote y decide entonces, con el dato del histórico delante, si vuelve a entrar o no.</p>
<p>El error habitual es seguir pidiendo por costumbre, o porque el comercial ofrece un rappel atractivo por volumen, sin pararte a calcular si ese descuento compensa el coste de tener el capital parado otros seis meses.</p>
<p><strong>Paso 4. Aplica el plan gradual</strong></p>
<p>Abordar todo el stock muerto de golpe es la forma más segura de no hacer nada. El plan que funciona en la práctica tiene tres fases. El primer mes es de diagnóstico y clasificación pura: nada de vender ni liquidar todavía, solo tener el mapa completo. Los meses dos y tres se dedican a intervenir sobre el "top 20" de cada zona, empezando por lo que más capital tiene inmovilizado. A partir del cuarto mes, la clasificación deja de ser un proyecto puntual y pasa a ser una revisión periódica más, con un protocolo claro para cualquier producto nuevo que entre en el catálogo.</p>
<p>Una farmacia de Sevilla que aplicó este método detectó 23.000 euros inmovilizados en su primer diagnóstico. Liquidó el 65% de ese stock, recuperando 14.950 euros, y reactivó otro 20% con acciones concretas de mostrador. En cuatro meses recuperó cerca de 18.000 euros de tesorería, redujo más de 5.000 euros anuales en costes operativos, y destinó el espacio liberado a dermocosmética, categoría que pasó a generar 11.200 euros adicionales al año.</p>
<p>El error más común en este paso es querer resolverlo todo en el mes uno, agotarse en el intento y abandonar antes de llegar a la fase de revisión periódica, que es la que de verdad evita que el problema vuelva a aparecer dentro de un año.</p>
<p><strong>Paso 5. Libera el espacio hacia lo que sí rota</strong></p>
<p>El objetivo final no es tener menos stock por tener menos stock: es reinvertir ese capital y ese espacio en lo que genera más rentabilidad. Cada hueco de mostrador o de trastienda que ganes al liquidar zona roja debería ir a parar a una categoría de alta rotación y buen margen, no quedarse vacío ni volver a llenarse de "por si acaso".</p>
<p>El error típico es justo ese: liberar el espacio y, sin darte cuenta, volver a ocuparlo con más referencias de baja rotación en los meses siguientes, porque nadie ha fijado una regla de qué entra en ese hueco.</p>
<h3>Errores frecuentes</h3>
<ul>
<li><strong>Clasificar por intuición en vez de por datos del programa de gestión.</strong> Corrección: saca siempre el listado real de ventas de los últimos doce meses antes de decidir nada.</li>
<li><strong>Aceptar ofertas por volumen sin calcular el coste de tener ese capital parado.</strong> Corrección: antes de aceptar un rappel, compara el descuento con el coste de oportunidad de inmovilizar ese dinero varios meses.</li>
<li><strong>Tratar toda la zona roja igual y liquidar productos estratégicos.</strong> Corrección: separa siempre estratégicos, en declive y "error" antes de tomar decisiones de salida.</li>
<li><strong>Intentar resolver todo el stock muerto en un solo mes.</strong> Corrección: sigue el plan gradual (diagnóstico, intervención en el top 20, revisión periódica) y no te saltes fases.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Abre tu programa de gestión y saca el listado de las 20 referencias sin ningún movimiento en los últimos tres meses. No hace falta actuar todavía sobre ninguna: solo tener esa lista delante ya es el primer paso real de la clasificación semáforo, y probablemente la primera vez que la ves completa.</p>
<h3>Cómo saber que funciona</h3>
<p>A los 30 días de empezar, comprueba estas tres señales:</p>
<ul>
<li><strong>El listado de referencias sin movimiento en tres meses es más corto que el que sacaste el primer día.</strong> Aunque solo hayas actuado sobre unas pocas, la lista debe reducirse, no crecer.</li>
<li><strong>Puedes nombrar de memoria tus 20 referencias de zona roja con más capital inmovilizado y qué vas a hacer con cada una.</strong> Si no lo tienes por escrito, el diagnóstico no está terminado.</li>
<li><strong>Has liberado al menos un hueco de mostrador o de trastienda y sabes qué categoría de zona verde lo va a ocupar.</strong> Un hueco vacío o vuelto a llenar de "por si acaso" es la señal de que el método no se ha aplicado hasta el final.</li>
</ul>
<h3>Para seguir</h3>
<p>El descargable de esta píldora, «Checklist: clasificación de inventario por rotación» (PDF), está justo debajo, en "Recursos descargables": te da la plantilla para extraer los datos, los criterios de las tres zonas y la tabla para registrar tu top 20 y tu plan de acción por categoría.</p>
$c$, $r$[{"title": "Checklist: clasificación de inventario por rotación", "url": "/recursos/impulso-n05-inventario-rotacion.pdf", "type": "pdf", "resource_id": "7bfcc4a3-ca9d-44ab-8752-5fc0c07aa4c2"}]$r$::jsonb),
  ('fp-pildora-categorias-responsables', 'fp-pildora-categorias-responsables-l1', $c$
<h3>El problema</h3>
<p>Estimación sectorial: la gestión del personal es uno de los principales desafíos que señalan los titulares de farmacia, por delante incluso de la presión de márgenes o la competencia digital. Y tiene sentido: has invertido en formación técnica, en mejorar el surtido, en optimizar compras. Pero rara vez has invertido el mismo tiempo en tu equipo como activo, no como coste.</p>
<p>Un equipo desconectado no lo dice en voz alta. Lo notas en el mostrador antes que en ningún informe: conversaciones que se limitan a lo imprescindible ("¿dónde está X producto?", "¿quién cierra hoy?"), cero propuestas de mejora, resistencia callada a cualquier cambio y esa frase que lo resume todo, "no es mi responsabilidad". Las reuniones, si las hay, se llenan de quejas sin ninguna propuesta detrás. Es fácil confundir estas señales con mal carácter o falta de profesionalidad, cuando en realidad son síntomas de una desconexión más profunda con el proyecto.</p>
<p>El coste no es solo de ambiente. Estimación sectorial: un equipo desmotivado hace de media un 37% menos de recomendaciones complementarias, y el 78% de los pacientes puede notar cuando el personal no está comprometido, aunque nunca lo diga en voz alta. A eso se suma la rotación: sustituir a un técnico ya formado supera con facilidad los 3.000 euros solo en tiempo de adaptación y formación. Cada persona desmotivada, en definitiva, se traduce en menos venta cruzada y en una experiencia peor para quien entra por la puerta.</p>
<h3>Por qué pasa</h3>
<p>Aquí está la paradoja: estimación sectorial, la mayoría de las farmacias forma a su equipo en producto de forma regular, pero muy pocas forman o estructuran nada en torno a la motivación y el compromiso. Se invierte en saber qué vender, no en por qué merece la pena venderlo bien. Y el número de farmacias que tiene un sistema de incentivos más allá del salario base es todavía menor.</p>
<p>La causa de fondo no es que tu equipo no quiera implicarse ni que tú no sepas liderar. Es que, en la mayoría de las farmacias, la responsabilidad se reparte sin autoridad. Se le pide a alguien que "se ocupe" de una sección, pero las decisiones de pedido, el diseño del lineal o la formación siguen centralizadas en el titular. Sin margen real para decidir, no hay nada que sentir como propio. Y sin nada propio, cuesta mucho pedir iniciativa.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Identifica el perfil motivacional de cada miembro del equipo</strong></p>
<p>No existe un sistema de motivación universal: cada persona responde a estímulos distintos. En una farmacia suelen convivir cinco perfiles: el sanitario vocacional, que busca propósito e impacto real en el paciente; el desarrollador de categoría, que quiere especializarse y tener autonomía sobre un área; el equilibrista familiar, que valora la estabilidad y la conciliación por encima de casi todo; el impulsor de equipo, con liderazgo natural y buenas habilidades sociales; y el técnico especialista, orientado a la excelencia y al método.</p>
<p>Obsérvalos en el día a día antes de etiquetarlos: quién pregunta por el porqué de una recomendación, quién pide cambiar turnos por conciliación, quién propone ideas sin que se las pidan. Un titular que reorganizó así su equipo lo resumía de esta manera: cuando entendió que cada persona se motivaba de forma distinta, pudo personalizar el sistema de incentivos y el resultado fue inmediato, más satisfacción y mejor rendimiento. El error más habitual en este paso es asumir que todo el equipo se motiva igual y aplicar el mismo gesto (una paga extra, una felicitación genérica) a personas que necesitan cosas muy distintas.</p>
<p><strong>Paso 2. Asigna categorías responsables</strong></p>
<p>Entrega a cada persona una categoría completa (dermocosmética, nutrición, infantil, la que tenga sentido en tu farmacia) con autoridad real sobre pedidos, merchandising y formación interna de esa categoría. No es repartir tareas de reposición, es repartir un trozo de negocio con capacidad real de decidir sobre él.</p>
<p>En una farmacia se asignó la categoría de dermocosmética a una técnico especialmente interesada en el área. En seis meses, las ventas de esa categoría aumentaron un 27% y las devoluciones por caducidad bajaron un 64%. La clave no fue solo darle la responsabilidad: fue darle también la autoridad para cambiar cosas de verdad, desde el pedido hasta el expositor. El error que más se repite en este paso es justo el contrario: seguir decidiendo tú los pedidos y el lineal "para no arriesgar", y dejarle a la otra persona solo la tarea de reponer. Eso no es una categoría responsable, es la misma reposición de siempre con un nombre más bonito.</p>
<p><strong>Paso 3. Fija KPIs claros por categoría</strong></p>
<p>Sin números, la responsabilidad no se puede medir ni reconocer, y sin reconocimiento, la motivación se apaga en pocas semanas. Cada categoría necesita sus propios indicadores: rotación de producto, margen, número de clientes fidelizados o, en categorías como infantil, familias que compran de forma completa y tasa de renovación.</p>
<p>Una farmacia de barrio con cuatro empleados que venía de tres cambios de personal en dieciocho meses y una venta cruzada del 7% asignó cuatro categorías responsables con sus KPIs propios. En seis meses, la venta cruzada subió al 23%, la facturación creció un 16% y no hubo ni una baja de personal. El error habitual aquí es fijar solo la cifra de caja del día, que depende de mil factores ajenos a la categoría, en lugar de un indicador propio que la persona responsable pueda de verdad influir con sus decisiones.</p>
<p><strong>Paso 4. Combina incentivos inmediatos e individuales con periódicos y colectivos</strong></p>
<p>Los incentivos más efectivos no dependen solo del dinero, que además tiene un límite marcado por el convenio. Combina gestos inmediatos e individuales (feedback específico y concreto, flexibilidad puntual, prioridad para elegir tareas) con gestos periódicos y colectivos (celebrar los objetivos trimestrales, dar voz en decisiones estratégicas, financiar alguna actividad de equipo). Y dentro de lo económico, complementa el bonus por objetivos con cosas que no cuestan lo mismo pero pesan igual: días adicionales, acceso a formación premium, reconocimiento delante del resto del equipo.</p>
<p>El error más frecuente es pensar que, como el convenio limita lo económico, no queda margen para incentivar. Justo al revés: cuanto más limitado esté el dinero, más peso tiene todo lo que no cuesta nada, la flexibilidad, la voz en las decisiones, el reconocimiento explícito.</p>
<p><strong>Paso 5. Convierte el feedback en un sistema continuo</strong></p>
<p>La motivación no se sostiene con un evento puntual, una cena de equipo o un bono navideño una vez al año. Funciona como un sistema que necesita atención constante: reuniones individuales breves y periódicas dan mejor resultado que cualquier gesto anual. Un consultor de liderazgo farmacéutico lo planteaba así: implementar reuniones de quince minutos cada dos semanas es, por sí solo, el cambio con mayor impacto inmediato, y estimación sectorial, puede reducir la rotación en cerca de un 40% en el primer trimestre.</p>
<p>El error que más veces se repite en este último paso es guardar el feedback para la evaluación anual o para cuando algo va mal. Si la única vez que hablas con alguien de su trabajo es para corregir un fallo, el feedback deja de sentirse como reconocimiento y empieza a sentirse como una amenaza.</p>
<h3>Errores frecuentes</h3>
<ul>
<li>Delegar la tarea pero no la autoridad: seguir decidiendo tú los pedidos o el lineal de una categoría que "en teoría" lleva otra persona. Corrección: si asignas una categoría, cede también la decisión sobre pedidos, merchandising y formación de esa categoría.</li>
<li>Medir con la caja del día en vez de con KPIs propios de la categoría. Corrección: define desde el primer día un indicador que la persona responsable pueda influir de verdad (rotación, margen, fidelización).</li>
<li>Reducir el incentivo a lo económico y darlo por agotado en cuanto choca con el convenio. Corrección: combina reconocimiento inmediato, participación en decisiones y flexibilidad horaria con lo económico, no en su lugar.</li>
<li>Tratar la motivación como un acontecimiento (la cena de Navidad, el bono anual) en vez de como una rutina. Corrección: instaura reuniones individuales breves y periódicas, cada dos semanas es un buen punto de partida.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Escribe en un papel el nombre de cada persona de tu equipo y, al lado, qué perfil motivacional crees que encaja mejor con cada una (sanitario vocacional, desarrollador de categoría, equilibrista familiar, impulsor de equipo o técnico especialista). No hace falta acertar a la primera: es el punto de partida para personalizar cómo reconoces el trabajo de cada uno, y el primer paso para decidir a quién le vas a entregar la primera categoría responsable.</p>
<h3>Cómo saber que funciona</h3>
<p>A los 30 días de poner en marcha el sistema, busca estas tres señales, todas observables sin necesidad de esperar meses:</p>
<ul>
<li>La persona responsable de una categoría propone un cambio de pedido, de expositor o de precio sin que se lo hayas pedido tú. Es la primera prueba de que ha asumido la autoridad, no solo la tarea.</li>
<li>El KPI propio de esa categoría (rotación, mermas por caducidad, margen) se mueve en la dirección correcta frente al mes anterior, aunque sea un movimiento pequeño.</li>
<li>Empiezan a aparecer frases de propiedad ("mi categoría", "he cambiado esto", "he mirado los números") en lugar de "no es mi responsabilidad".</li>
</ul>
<p>Los resultados grandes, como el aumento del 27% en ventas o el 16% en facturación que veías en los ejemplos de esta píldora, tardaron varios meses en llegar. A 30 días no busques esa cifra: busca la señal de que la persona ya se comporta como dueña de su categoría.</p>
<h3>Para seguir</h3>
<p>El descargable de esta píldora, «Plan de incentivos para tu equipo» (PDF), está justo debajo, en "Recursos descargables".</p>
$c$, $r$[{"title": "Plan de incentivos para tu equipo", "url": "/recursos/impulso-n04-incentivos.pdf", "type": "pdf", "resource_id": "b7c2561d-99ca-4923-9db5-ec3268302432"}]$r$::jsonb),
  ('fp-pildora-rentabilidad-categorias', 'fp-pildora-rentabilidad-categorias-l1', $c$
<h3>El problema</h3>
<p>Camina por tu propia farmacia como si fueras un cliente y fíjate en qué ocupa las mejores posiciones: la altura de los ojos, el primer mueble al entrar, el lineal junto a caja. En muchas farmacias esas posiciones las ocupa lo que siempre ha estado ahí, no lo que más rentabilidad genera por metro cuadrado. Un análisis de farmapro sobre más de 150 farmacias españolas encontró que, de media, hasta un 40% de la superficie comercial está desaprovechada o asignada a categorías de bajo rendimiento.</p>
<p>Se nota en cosas muy concretas. Un titular de Barcelona que participó en ese análisis, Antonio Sánchez, lo explicaba así: al renovar su farmacia hace unos años, repartió el espacio "basándonos en intuiciones y en cómo lo hacían otras farmacias". Solo cuando analizó la rentabilidad por categoría descubrió que dedicaba un 30% del espacio a productos que generaban apenas un 10% de su margen. No es un caso aislado: es lo que pasa cuando el espacio se decide por costumbre y no se revisa nunca con datos.</p>
<p>El coste no es solo estético. La regla de Pareto se cumple con fuerza en el mostrador: aproximadamente el 20% de tus productos genera el 80% de tu rentabilidad. Si ese 20% no tiene el espacio que le corresponde, cada metro cuadrado mal asignado es dinero que no llega a tu cuenta de resultados. Y como es un coste invisible, que no aparece en ningún ticket ni genera ninguna alarma, puede llevar años sin corregirse.</p>
<h3>Por qué pasa</h3>
<p>No es un problema de gestión descuidada. La farmacia española ha pasado de ser, sobre todo, un punto de dispensación de medicamentos a un establecimiento con decenas de categorías: dermocosmética, suplementación, ortopedia, infantil, cuidado capilar especializado, y sigue creciendo. Cada categoría nueva se fue añadiendo cuando tuvo sentido (un proveedor interesante, una demanda de tus pacientes, una moda del sector), pero casi nunca alguien se sentó a rediseñar el conjunto desde cero.</p>
<p>El resultado es un espacio que ha crecido por acumulación, no por diseño. Calcular la rentabilidad real por metro cuadrado exige cruzar datos de ventas, margen y superficie que normalmente viven en sitios distintos (el TPV, el proveedor, tu memoria), así que la mayoría de farmacias no lo hace nunca. Sin ese dato, decide la costumbre: lo que lleva ahí diez años se queda ahí diez años más, aunque haya dejado de ganarse su sitio.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Mide la venta y el margen por metro cuadrado</strong></p>
<p>El primer paso es poner un número, aunque sea aproximado, a cada categoría. Necesitas dos datos de los últimos 12 meses: las ventas y el margen bruto de cada categoría, y los metros cuadrados (o metros lineales de estantería) que ocupa. La mayoría de programas de TPV exportan ventas por familia de producto sin mucho esfuerzo; la superficie puedes medirla a ojo con una cinta métrica un domingo por la tarde, no hace falta precisión de arquitecto.</p>
<p>Con esos dos datos monta tu propio mapa de calor: verde para las zonas que superan los 1.000 euros de margen por metro cuadrado al año, amarillo entre 600 y 1.000, rojo por debajo de 600. Son umbrales de referencia del análisis de farmapro, no una norma fija: sirven para comparar tus propias categorías entre sí.</p>
<p>El error más habitual es medir solo ventas y olvidar el margen. Una categoría puede vender mucho y dejar poco beneficio, como cierta parafarmacia básica con márgenes ajustados, mientras otra vende menos con un margen muy superior. Si solo miras ventas, acabas dando más espacio a lo que menos rentabilidad te deja.</p>
<p><strong>Paso 2. Clasifica cada categoría en la matriz de decisión</strong></p>
<p>Con los datos del paso 1, sitúa cada categoría en una matriz de dos ejes: rentabilidad por metro cuadrado y potencial de crecimiento a corto plazo. Salen cuatro tipos. La categoría "estrella" tiene alta rentabilidad y alto potencial: merece más espacio y una posición destacada. La "vaca" ya rinde bien pero tiene poco recorrido de crecimiento: mantén su espacio, no lo amplíes, pero cuida su ubicación. La "interrogante" rinde poco hoy pero tiene potencial: pruébala en una ubicación estratégica antes de decidir si crece o desaparece. Y la "perro", baja rentabilidad y bajo potencial, es la que debe ceder espacio.</p>
<p>En dermocosmética facial, por ejemplo, el análisis de farmapro encontró márgenes de entre el 35% y el 45%, con farmacias que al crear una zona diferenciada y personal formado reportaron incrementos del 32% en ventas en seis meses: un candidato claro a "estrella". Marta Gómez, titular en Valencia, aplicó esta matriz y descubrió que tenía "categorías perro en las mejores ubicaciones, mientras que auténticas estrellas estaban escondidas". Tras reorganizar, su rentabilidad subió un 23%.</p>
<p>El error típico es clasificar categorías demasiado amplias. "Dermocosmética" en bloque puede esconder una facial estrella y una corporal vaca. Cuanto más concreta la categoría, más útil es la clasificación.</p>
<p><strong>Paso 3. Encuentra tu top 5 y tu bottom 5</strong></p>
<p>Ordena tus categorías de mayor a menor rentabilidad por metro cuadrado y separa las cinco mejores de las cinco peores. Después compara cuánto espacio ocupa cada grupo. En una farmacia bien ajustada, el top 5 debería tener bastante más espacio que el bottom 5 (como referencia orientativa, el análisis de farmapro señala que debería triplicarlo, no ser parecido ni menor).</p>
<p>La Farmacia López, en Madrid, aplicó este criterio y redujo un 30% el espacio de parafarmacia básica para ampliar su zona de dermocosmética. El resultado fue un 17% más de rentabilidad global sin perder ventas relevantes en las categorías reducidas: dar menos espacio a algo no significa dejar de venderlo, solo dejar de sobrededicarle metros que no se gana.</p>
<p>El error más común es comparar por volumen de ventas históricas en vez de por rentabilidad real. Una categoría puede llevar años vendiéndose mucho por costumbre del cliente, no porque sea la que más te conviene destacar.</p>
<p><strong>Paso 4. Busca adyacencias con sentido comercial</strong></p>
<p>Una vez sabes qué categorías merecen más espacio, decide dónde colocarlas. Las adyacencias con sentido comercial (categorías complementarias colocadas cerca) facilitan que el cliente descubra un producto relacionado sin tener que buscarlo: protección solar junto a productos para después del sol en primavera es el ejemplo más evidente, pero funciona igual con microcategorías como "piernas cansadas" (medicamentos, complementos y medias juntos) o "rincón del deportista" (vendajes, complementos y dermocosmética específica en un mismo punto).</p>
<p>La Farmacia Martínez, en Barcelona, creó siete microcategorías así y logró un 34% más de venta cruzada entre productos complementarios. La Farmacia Rodríguez, en Sevilla, fue un paso más allá con expositores que rotan semanalmente entre cinco ubicaciones, y consiguió un 21% más de ventas en los productos destacados en esos puntos.</p>
<p>El error frecuente es organizar el espacio por proveedor o por orden alfabético: cómodo para reponer, pero invisible para el cliente, que no compra por proveedor sino por necesidad.</p>
<p><strong>Paso 5. Implementa de forma progresiva y mide</strong></p>
<p>No cambies toda la farmacia en un fin de semana. Implementa los ajustes por fases (una zona, luego otra) y mide siempre el antes y el después con los mismos indicadores del paso 1: ventas y margen por metro cuadrado. Si cambias todo a la vez, pierdes la referencia para saber qué movimiento concreto ha funcionado y cuál no.</p>
<p>El caso más completo del análisis de farmapro es la Farmacia Jiménez, en Zaragoza, con 120 metros cuadrados de zona de venta. Redujo un 40% el espacio de OTC genérico, creó tres microcategorías de alta rentabilidad, amplió la dermocosmética con un córner especializado e implementó un expositor dinámico semanal. Resultados a los seis meses: un 27% más de rentabilidad global, un 34% más de ticket medio y un 41% más de ventas en dermocosmética, sin obras ni grandes inversiones.</p>
<p>El error que más se repite aquí es justo lo contrario a la prudencia del principio: hacerlo todo de golpe, sin medir, y acabar sin saber si el resultado se debe a la reorganización o a cualquier otra cosa que pasó ese mes.</p>
<h3>Errores frecuentes</h3>
<ul>
<li>Medir solo ventas y no margen: una categoría con mucho movimiento puede dejar poco beneficio. Corrígelo cruzando siempre ventas y margen antes de decidir el espacio.</li>
<li>Reorganizar toda la farmacia de una vez: sin fases, no sabes qué cambio funcionó. Corrígelo implementando zona a zona y comparando cada una con su propio antes y después.</li>
<li>Fiarte de la intuición o de "cómo lo hacen otras farmacias": la costumbre no es un dato. Corrígelo con los números de tu propio TPV, aunque sean aproximados.</li>
<li>Dejar el nuevo planograma fijo para siempre: un espacio bien pensado hoy deja de serlo en unos meses. Corrígelo revisando la distribución al menos una vez por temporada.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Coge un papel y dibuja un plano muy simple de tu farmacia: mostrador, lineales, escaparate, zona de espera. Marca cada zona con uno de tres colores, verde, amarillo o rojo, según lo que crees, a ojo, que genera más o menos rentabilidad por metro cuadrado. No necesitas los datos exactos todavía, este boceto es solo tu primera hipótesis. Guárdalo: cuando completes el paso 1 con datos reales, compáralo y verás dónde acertabas y dónde no.</p>
<h3>Cómo saber que funciona</h3>
<p>A los 30 días de aplicar los primeros cambios, mira estas tres señales:</p>
<ul>
<li>La venta por metro cuadrado de las categorías que ampliaste sube frente al mismo periodo del mes anterior. Si no se mueve, revisa si de verdad les diste una posición mejor o solo más metros.</li>
<li>El ticket medio sube ligeramente. Es la señal de que las adyacencias están funcionando: el cliente encuentra el producto complementario y se lo lleva.</li>
<li>El espacio liberado a las categorías "perro" no genera una caída de ventas totales. Si las ventas globales aguantan con menos metros dedicados a esas categorías, confirma que ese espacio estaba mal aprovechado.</li>
</ul>
<h3>Para seguir</h3>
<p>Justo debajo, en "Recursos descargables", tienes la guía "Distribución estratégica por categorías de alto margen": una plantilla para calcular la rentabilidad por metro cuadrado de tus propias categorías, clasificarlas en la matriz de decisión y planificar tu redistribución paso a paso.</p>
$c$, $r$[{"title": "Distribución estratégica por categorías de alto margen", "url": "/recursos/impulso-n03-categorias-alto-margen.pdf", "type": "pdf", "resource_id": "d2ef5da9-afaf-47c8-adf7-d1b7daf78336"}]$r$::jsonb),
  ('fp-pildora-corner-dermocosmetica', 'fp-pildora-corner-dermocosmetica-l1', $c$
<h3>El problema</h3>
<p>Entras en tu farmacia por la puerta de atrás y pasas junto a la zona de dermocosmética sin mirarla, porque ya la conoces de memoria: dos o tres estanterías apretadas, marcas mezcladas sin criterio y la misma iluminación que en el resto del lineal. Para ti es paisaje. Para el paciente que sí se para, es un muro de cajas que no sabe por dónde empezar, y si nadie le ayuda en los primeros veinte segundos, sigue caminando hacia la caja con lo que ya llevaba en la mano.</p>
<p>Esto se nota cada día en el mostrador. Un paciente pregunta por "algo para las manchas" o "una crema que no le haga granos", y la respuesta suele ser señalar la estantería y leer en voz alta lo que dice el envase, porque es lo único que hay para ofrecer: no hay diagnóstico, no hay rutina completa, no hay prueba de producto. El paciente compara ese servicio con lo que puede leer solo en internet, y en ese terreno la farmacia siempre pierde, porque compite por precio en lugar de competir por criterio profesional.</p>
<p>Lo que cuesta esto no es solo la venta que se escapa hoy. Es una categoría con márgenes de entre el 35% y el 45%, muy por encima del margen medio de la farmacia, que se queda infrautilizada mientras el resto de la cuenta de resultados se estrecha (estimación sectorial). Y no es un problema puntual: muchas farmacias dedican menos del 10% de su espacio comercial y menos del 5% del tiempo de formación del equipo a esta categoría, tratándola como un lineal más en lugar de como el motor de rentabilidad que puede llegar a ser (estimación sectorial).</p>
<h3>Por qué pasa</h3>
<p>No es que el titular no vea la oportunidad. Es que la dermocosmética se monta con la lógica de la parafarmacia general: se compra lo que trae el representante, se coloca donde queda hueco y se confía en que el propio envase haga el trabajo de venta. Es una gestión razonable para OTC de rotación rápida, pero la dermocosmética funciona con otra lógica: el paciente no busca un producto, busca una solución para un problema de piel concreto, y esa solución solo se la puede dar alguien que le pregunte, le mire y se la explique.</p>
<p>El otro motivo de fondo es que casi nadie ha dedicado tiempo a formar al equipo específicamente en esto. La formación que llega de los laboratorios suele ser comercial (características del producto), no clínica (cómo reconocer un tipo de piel y construir una rutina). Sin esa base, hasta el auxiliar con más ganas del mundo acaba repitiendo lo que pone en la caja, y eso el paciente ya puede leerlo solo, sin necesitar a nadie detrás del mostrador.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Diagnostica tu punto de partida</strong></p>
<p>Antes de mover un solo producto necesitas datos, no intuición. Saca de tu programa de gestión qué porcentaje de tu facturación de parafarmacia representa hoy la dermocosmética, cuántas marcas tienes activas y, de esas marcas, cuáles rotan de verdad frente a las que llevan meses acumulando polvo. Diez minutos con el listado de compras del último trimestre bastan para tener la fotografía.</p>
<p>En una farmacia real esto se traduce en una tabla sencilla: marca, facturación del trimestre, número de referencias, margen medio. No hace falta un programa sofisticado, vale un Excel a mano. El error que más se repite en este paso es saltárselo por parecer obvio ("ya sé cuáles venden") y lanzarse directamente a comprar mobiliario nuevo: sin el dato de partida no hay forma de medir después si la transformación ha funcionado de verdad.</p>
<p><strong>Paso 2. Reduce el número de marcas y aumenta la profundidad</strong></p>
<p>Con el diagnóstico en la mano, el instinto habitual es añadir marcas nuevas para "tener más oferta". Es justo el camino contrario al que funciona. Mejor trabajar en profundidad 3-5 marcas, con formación real del equipo en cada una de ellas, que mantener 15 marcas con tres referencias cada una que nadie en el mostrador domina de verdad.</p>
<p>El motivo es simple: tu equipo puede aprender a fondo cuatro o cinco gamas (sus activos, sus texturas, para qué tipo de piel funciona cada una), pero no quince. Y esa seguridad al recomendar es precisamente lo que convierte una consulta en la venta de una rutina completa, en lugar de en un producto suelto. El error frecuente aquí es eliminar marcas por corazonada; hazlo siempre a partir del dato del Paso 1, dando prioridad a las que ya generan la mayor parte de tu facturación en la categoría.</p>
<p><strong>Paso 3. Organiza el espacio por necesidad del paciente</strong></p>
<p>Aquí entran dos de los elementos que más cambian la percepción del paciente: la ubicación y la luz. La ubicación del corner debe ser visible desde la entrada o desde la zona de espera, no un rincón al fondo que solo se descubre si ya se sabía que existía. Y la luz debe ser distinta a la del resto del lineal: más cálida y más directa sobre el producto, para que el cliente perciba, físicamente, que ha entrado en un espacio distinto al resto de la farmacia.</p>
<p>Organiza además la exposición por necesidad del paciente (piel sensible, manchas, hidratación, acné) en lugar de por marca o laboratorio: así el cliente encuentra su solución sin tener que preguntar, y tu equipo puede recomendar cruzando gamas dentro de una misma necesidad. El error habitual es mover los productos pero dejar la misma luz de fluorescente de siempre; el cliente nota el cambio de orden, pero no el cambio de categoría si el espacio sigue pareciendo el mismo pasillo de antes.</p>
<p><strong>Paso 4. Forma a tu equipo en un protocolo de consulta breve</strong></p>
<p>El cuarto elemento de la transformación es el gesto del equipo, y es el que más vende de los cuatro. No hace falta convertir a nadie en dermatólogo: basta con un protocolo breve y repetible. Escuchar la preocupación del paciente (dos minutos, sin interrumpir), observar el tipo de piel a simple vista, recomendar una rutina completa (nunca un producto suelto) y programar un seguimiento antes de que el paciente se vaya del mostrador.</p>
<p>Practicadlo entre vosotros antes de estrenarlo con pacientes reales: un compañero hace de paciente, otro sigue el protocolo paso a paso, y al final comentáis qué ha faltado. El error que más se repite es saltarse la escucha y pasar directamente a recomendar, lo que convierte la consulta en una venta forzada en vez de en un diagnóstico honesto; el paciente lo nota enseguida y desconfía.</p>
<p><strong>Paso 5. Ofrece un servicio de diagnóstico de piel</strong></p>
<p>El último elemento es la prueba de producto, y cierra el círculo de los cuatro que promete esta píldora. Ofrece un diagnóstico de piel de 10-15 minutos, sin coste, en el que además de escuchar y observar, aplicas el producto recomendado en la mano o el antebrazo del paciente para que note la textura antes de decidir. Este gesto multiplica la conversión porque el paciente experimenta el producto en lugar de imaginárselo por la foto del envase.</p>
<p>Hazlo siempre dentro del criterio profesional: se recomienda lo que el paciente necesita, no lo que tiene más margen. El error frecuente es convertir la muestra en un regalo suelto sin seguimiento; una muestra sin conversación posterior no genera fidelización, mientras que una muestra ligada a una recomendación y a un seguimiento a los quince días sí la genera.</p>
<h3>Errores frecuentes</h3>
<ul>
<li>Comprar mobiliario o cambiar la iluminación antes de tener el diagnóstico del Paso 1: se gasta dinero sin saber si el problema real es de espacio, de surtido o de formación.</li>
<li>Mantener 10 marcas o más "por si acaso": ninguna se trabaja a fondo y el equipo no puede recomendar con seguridad ninguna de ellas.</li>
<li>Formar al equipo una sola vez y darlo por hecho: el protocolo de consulta se olvida en pocas semanas si no se practica y se recuerda con regularidad.</li>
<li>Ofrecer el diagnóstico de piel como un trámite rápido, sin prueba de producto ni seguimiento posterior: se pierde justo la parte que más convierte, que es que el paciente toque y sienta el producto.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Coge el listado de tus marcas de dermocosmética y marca cuáles generan la mayor parte de tu facturación en la categoría. Esas son tus marcas clave: las que vas a trabajar en profundidad, formar a fondo y colocar en el mejor sitio del corner. El resto son candidatas a sustituirse por más referencias de las que ya funcionan.</p>
<h3>Cómo saber que funciona</h3>
<p>A los 30 días de empezar, mira estas tres señales:</p>
<ul>
<li>El número de consultas de diagnóstico de piel realizadas por semana ha subido respecto al mes anterior, aunque solo sean dos o tres más.</li>
<li>El ticket medio de la categoría dermocosmética ha crecido, porque el equipo está recomendando rutinas de varios pasos en lugar de productos sueltos.</li>
<li>El equipo cita, sin mirar el envase, al menos dos activos de cada una de vuestras marcas clave y para qué tipo de piel sirve cada uno.</li>
</ul>
<p>Si las tres se cumplen, el corner está funcionando. Si ninguna se mueve todavía, revisa primero la formación del Paso 4: casi siempre el cuello de botella está ahí, no en el espacio.</p>
<h3>Para seguir</h3>
<p>Para poner en marcha esta transformación paso a paso, con calendario e inversión estimada por fases, tienes el plan "Transformación de zona tradicional a corner dermocosmético" (publicado como «Plan de transformación digital», PDF), justo debajo, en "Recursos descargables".</p>
<p><strong>Nota deontológica:</strong> la recomendación dermocosmética debe basarse siempre en la necesidad real del paciente, nunca prometer resultados clínicos concretos, y derivar al dermatólogo cuando la consulta exceda el ámbito de la farmacia.</p>
$c$, $r$[{"title": "Plan de transformación digital", "url": "/recursos/impulso-n17-plan-transformacion.pdf", "type": "pdf", "resource_id": "f79757d3-c8a4-4d1c-861f-dcab47142472"}]$r$::jsonb),
  ('fp-pildora-cliente-que-no-vuelve', 'fp-pildora-cliente-que-no-vuelve-l1', $c$
<h3>El problema</h3>
<p>El cliente más peligroso no es el que se queja. Es el que sonríe, paga y no vuelve nunca más. Una encuesta a más de 500 personas que habían dejado su farmacia habitual encontró que el 78% nunca comunicó su insatisfacción antes de irse: un día decidieron probar otro establecimiento y no volvieron. Ni una palabra en el mostrador, ni una reclamación, ni una pista.</p>
<p>En el día a día esto no se ve como una fuga, se ve como normalidad. Un martes con menos gente de la que recuerdas. Una tarjeta de fidelización que hace semanas que no pasas por el lector. Un cliente crónico con el que antes coincidías cada mes y ahora, si haces memoria, no sabrías decir cuándo fue la última vez. No hay ningún aviso porque nadie te avisa: simplemente, deja de aparecer.</p>
<p>El coste de no verlo a tiempo es real y se puede poner en números. Según la Asociación Española de Marketing Farmacéutico, conseguir un cliente nuevo cuesta entre 5 y 7 veces más que conservar uno que ya confía en ti, y subir la retención de clientes solo un 5% puede traducirse en entre un 25% y un 95% más de beneficio. Dicho de otro modo: cada cliente habitual que se va en silencio no es una baja cualquiera, es una fuga con un precio concreto que rara vez se contabiliza porque nunca aparece como una queja en ningún sitio.</p>
<h3>Por qué pasa</h3>
<p>No es que gestiones mal a tus clientes. Es que el mostrador no da tiempo para leer señales pequeñas cuando hay cola, dos empleados y un cliente esperando el precio de un pedido especial. Las señales de alarma son minúsculas una a una: comprar solo lo justo en vez de la rutina completa, hablar menos, no pedir consejo. Ninguna, por separado, parece nada.</p>
<p>Y a esto se suma un motivo más de fondo, que tampoco depende de ti: a la mayoría de las personas les incomoda decir en persona que algo no les ha gustado. En la misma encuesta, el 41% de los clientes que abandonaron reconoció que le resultaba incómodo expresar una crítica directa a alguien con quien tenía trato cercano, y el 37% pensaba que decirlo tampoco iba a cambiar nada. Así que en lugar de hablar, prueban otra farmacia. Si esa otra farmacia les convence un poco más, no vuelven, y tú nunca llegas a enterarte de que hubo un motivo.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Detecta las señales silenciosas</strong></p>
<p>No busques quejas, porque no van a llegar. Busca cambios de comportamiento en las personas que ya conoces: menos frecuencia de visita, menos categorías de compra (solo lo imprescindible en vez de la rutina completa de siempre), menos conversación en el mostrador, dejar de usar la tarjeta de fidelización, o preguntar si tal producto se puede conseguir en otro sitio. Esta última es la señal más clara de todas: un cliente que pregunta por la competencia ya la está comparando contigo.</p>
<p>En la práctica, esto se detecta mejor de lo que parece porque tú y tu equipo ya conocéis a estos clientes de memoria. El error habitual es no pararse a pensarlo de forma sistemática: la señal pasa por delante todos los días y nadie la anota en ningún sitio hasta que, un buen día, cae en la cuenta de que hace meses que no ve a alguien.</p>
<p><strong>Paso 2. Clasifica a tus clientes habituales en un semáforo de riesgo</strong></p>
<p>Coge tu lista de clientes más habituales y clasifícalos en tres colores: verde (relación estable, compras regulares), amarillo (algún cambio de patrón, algo ha cambiado pero no es concluyente) y rojo (señales claras de distanciamiento, hace tiempo que no lo ves o su comportamiento ha cambiado del todo). No hace falta un programa complicado: una lista con un color al lado de cada nombre ya funciona.</p>
<p>Lo que aporta este paso no es la clasificación en sí, sino que te obliga a mirar a cada cliente por separado en vez de fiarte de la sensación general de que "el negocio va bien". Puedes tener la caja llena y, a la vez, estar perdiendo silenciosamente a una parte de tus clientes de siempre porque los nuevos tapan el hueco que dejan los que se van.</p>
<p><strong>Paso 3. Presta especial atención a los momentos críticos</strong></p>
<p>Hay situaciones donde el riesgo de perder a un cliente se dispara: la primera vez que acude con una necesidad importante (un tratamiento crónico, un problema de salud relevante), cualquier situación de desabastecimiento, y los cambios en tu propia farmacia (reformas, personal nuevo, cambios de horario). En estos momentos no es la circunstancia en sí lo que hace perder al cliente (un desabastecimiento puntual es comprensible), sino cómo se gestiona: si el cliente se va sin una alternativa clara o sin sentir que le has dedicado atención, ese momento queda grabado.</p>
<p>Vigilar estos momentos es más rentable que vigilar todo lo demás por igual, porque concentran una parte desproporcionada de las bajas. Si tu farmacia va a pasar por una reforma o vas a incorporar personal nuevo, este es precisamente el periodo en el que conviene reforzar la atención a los clientes de siempre, no relajarla.</p>
<p><strong>Paso 4. Actúa con las dos acciones que recuperan sin perseguir</strong></p>
<p>Cuando detectes una señal de alerta (un cliente en amarillo o en rojo), hay dos acciones concretas que funcionan sin resultar invasivas ni convertir el mostrador en un interrogatorio.</p>
<p>La primera es el diálogo de recuperación: una pregunta abierta y natural sobre algo que ya sabes de esa persona, del tipo "¿qué tal le fue con el tratamiento que le recomendamos la última vez?" o "¿sigue notando esas molestias de las que me habló?". No es una encuesta ni una llamada de retención, es la misma conversación de mostrador de siempre, solo que dirigida a alguien a quien llevas tiempo sin prestarle esa atención. La pregunta abre la puerta a que la persona cuente, sin presión, si algo no ha ido bien.</p>
<p>La segunda es la propuesta de valor ajustada: ofrecer algo pensado para la situación actual de esa persona, no una oferta genérica. Si detectaste que ha reducido su compra a lo imprescindible, puede ser información útil sobre un producto relacionado con lo que ya compra, o recordarle un servicio que ya ofreces y que quizá no sabe que tiene a su disposición. El objetivo no es descuentos, es demostrar que sigues prestando atención a lo suyo en concreto.</p>
<p>Estas dos acciones combinadas (preguntar y ajustar la propuesta) son las que marcan la diferencia entre perseguir a un cliente, que incomoda y suele funcionar al revés, y recuperarlo con naturalidad, que es lo que de verdad reengancha.</p>
<p><strong>Paso 5. Convierte la prevención en cultura de equipo</strong></p>
<p>La detección no puede depender solo de ti. Si el auxiliar que atiende habitualmente a un cliente nota un cambio pero no tiene dónde comentarlo, esa información se pierde. Monta un canal sencillo, aunque sea una libreta en el mostrador o un grupo interno, para que cualquiera del equipo pueda apuntar una señal o una sugerencia menor de un cliente en el mismo momento en que la percibe.</p>
<p>El error más habitual aquí es esperar a que la insatisfacción se acumule hasta convertirse en una queja formal antes de hacer algo. Para entonces, en la mayoría de los casos, el cliente ya ha decidido probar otro sitio. Cuanto antes recoja el equipo esa señal menor, antes se puede actuar con el paso 4.</p>
<h3>Errores frecuentes</h3>
<ul>
<li>Esperar a que el cliente se queje para actuar: la mayoría no lo va a hacer, así que si esperas la queja, esperas en vano. Actúa sobre las señales de comportamiento, no sobre las palabras.</li>
<li>Tratar a todos los clientes habituales por igual: sin una clasificación mínima (el semáforo del paso 2), la atención se reparte al azar y los clientes en rojo, que son los que más urgen, pasan desapercibidos entre los que están bien.</li>
<li>Confundir recuperación con descuento agresivo: ofrecer una rebaja grande en cuanto detectas una señal transmite urgencia y puede resultar contraproducente. La propuesta de valor ajustada del paso 4 funciona mejor cuando es específica, no cuando es barata.</li>
<li>Dejar la detección solo en manos del titular: si el equipo no participa, la mayoría de las señales silenciosas se pierden, porque suelen aparecer en conversaciones de mostrador que el titular no siempre presencia.</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Piensa en tus 10 clientes más habituales y marca junto a cada nombre un color: verde si su relación con la farmacia sigue igual de activa, amarillo si notas algún cambio (menos visitas, menos conversación), rojo si hace tiempo que no lo ves. Es tu primera auditoría de "clientes semáforo". Si alguno queda en rojo, elige uno solo y prepara la pregunta abierta del paso 4 para la próxima vez que lo veas o para llamarle esta misma semana.</p>
<h3>Cómo saber que funciona</h3>
<ul>
<li>A los 30 días, el número de clientes en rojo de tu lista inicial debería haber bajado: algunos habrán vuelto a amarillo o verde tras el diálogo de recuperación, y sabrás con nombre y apellido a cuáles no has llegado a tiempo.</li>
<li>El equipo empieza a comentar señales por iniciativa propia (un cliente que preguntó por otra farmacia, alguien que dejó de usar la tarjeta) sin que tengas que preguntarlo tú. Es la señal de que el canal del paso 5 funciona de verdad, no solo sobre el papel.</li>
<li>Notas menos sorpresas del tipo "hace meses que no veo a fulano": si la clasificación se mantiene viva, dejas de descubrir bajas con retraso y empiezas a anticiparte a ellas.</li>
</ul>
<h3>Para seguir</h3>
<p>Para no depender solo de la memoria, tienes justo debajo, en "Recursos descargables", la plantilla «Alerta temprana de clientes en riesgo»: te sirve para llevar el semáforo de riesgo del paso 2 sin tener que montarlo desde cero y para no perder de vista a quién le toca el diálogo de recuperación del paso 4.</p>
$c$, $r$[{"title": "Alerta temprana de clientes en riesgo", "url": "/recursos/impulso-n08-clientes-riesgo.pdf", "type": "pdf", "resource_id": "ffc3c782-cb92-443d-b7b3-542949e30ddc"}]$r$::jsonb),
  ('fp-pildora-cinco-palancas', 'fp-pildora-cinco-palancas-l1', $c$
<h3>El problema</h3>
<p>No todas las farmacias que trabajan mucho crecen. Puedes abrir todos los días, conocer a cada cliente por su nombre y salir agotado cada tarde, y aun así facturar exactamente lo mismo que hace tres años. Eso es lo que le pasa a la farmacia estancada: no pierde dinero, pero tampoco avanza, y la sensación de fondo es de cansancio sin recompensa.</p>
<p>Hay un segundo grupo, el de las farmacias que crecen a trompicones. Empiezan bien un trimestre (una campaña sale redonda, un servicio nuevo funciona) y al siguiente vuelven a caer, porque nadie ha sostenido lo que funcionó. El titular sabe que va en la dirección correcta, pero le falta sistema: hace las cosas bien un mes y se olvida al siguiente.</p>
<p>Y luego está la farmacia madura, la que crece poco pero de forma sostenida y predecible, con el titular con tiempo, beneficio y energía. Lo que la separa de las otras dos no es el local, ni la zona, ni la plantilla. Es que mueve las mismas cinco palancas, una detrás de otra, con disciplina. El coste de no saberlo es alto: meses de esfuerzo repartidos en todas direcciones que no se notan en la cuenta de resultados de diciembre.</p>
<h3>Por qué pasa</h3>
<p>La mayoría de titulares no fracasa por falta de ganas. Fracasa por falta de diagnóstico. Sin saber en qué momento está tu farmacia hoy (estancada, creciendo o madura), es imposible elegir bien qué mover primero: acabas copiando lo que le funciona a la farmacia de al lado, aunque esté en una fase distinta a la tuya.</p>
<p>El segundo motivo es la dispersión. Cuando por fin decides actuar, la tentación es hacerlo todo a la vez: mejorar la ficha de Google, lanzar un servicio nuevo, pedir reseñas y montar un calendario de campañas, todo el mismo trimestre. El resultado casi siempre es el mismo: ninguna de las cuatro llega a completarse del todo, y a los tres meses parece que no ha cambiado nada. No es un problema de esfuerzo, es un problema de foco.</p>
<h3>El método en 5 pasos</h3>
<p><strong>Paso 1. Visibilidad</strong></p>
<p>Se trata de que te encuentren antes de necesitarte, y esa batalla se libra en Google, en redes y en el escaparate, no en el mostrador. Si tu farmacia está estancada, empieza por lo más barato y con más retorno: completa tu ficha de Google (horario correcto, fotos actuales, reseñas pedidas de forma activa). Dedicarle dos horas un domingo puede traducirse en un 15-20% más de tráfico al mostrador en tres meses (estimación sectorial). Si estás creciendo, sostén un único canal social bien hecho antes de abrir tres a medias. Si eres madura, construye autoridad local con contenido propio: artículos sanitarios, colaboraciones con centros de salud, talleres abiertos. El error más repetido aquí es abrir perfiles en todas las redes a la vez y abandonarlos a las tres semanas: es peor tener un canal muerto que no tener ninguno.</p>
<p><strong>Paso 2. Conversión</strong></p>
<p>No basta con tener gente dentro: hay que conseguir que cada visita termine en la mejor decisión para esa persona, que a menudo incluye dos o tres productos en vez de uno solo. Si estás estancada, trabaja una sola categoría en profundidad, como la dermocosmética: convertir un rincón olvidado en un corner con formación al equipo puede llevar esa categoría del 8% al 25% de tu facturación en doce meses (estimación sectorial). Si creces, sistematiza la recomendación cruzada con protocolo, no de forma improvisada. Si eres madura, ofrece consulta especializada con cita previa. El error habitual es confundir esto con "vender más": no se trata de forzar el ticket, se trata de completar el consejo sanitario que esa persona necesitaba y no había pedido.</p>
<p><strong>Paso 3. Captación</strong></p>
<p>Es atraer al cliente que todavía no te conoce, y el dato que distingue a una farmacia madura de una estancada es simple: la madura sabe cuántos clientes nuevos entraron el mes pasado y de dónde vinieron. Si estás estancada, la vía más barata es pedir reseñas a los clientes satisfechos: una ficha con 200 reseñas y una nota alta se sitúa por delante de competidores con peor reputación digital, y el coste es prácticamente cero. Si creces, suma captación digital con llamada a la acción hacia la visita física, nunca hacia el envío a domicilio. Si eres madura, construye alianzas con otros profesionales de la salud (fisioterapeutas, dermatólogos, centros deportivos): una alianza bien trabajada puede traer entre 40 y 60 clientes al año (estimación sectorial). El error típico es pedir la reseña solo quien ya la habría dejado por iniciativa propia, en vez de pedirla siempre, en el momento justo tras una buena experiencia.</p>
<p><strong>Paso 4. Diversificación</strong></p>
<p>Consiste en convertir la farmacia en un centro de servicios y no solo de dispensación. Si estás estancada, elige uno solo para empezar, por ejemplo una cabina de medición (tensión, glucosa, peso) con seguimiento personalizado: inversión mínima y retorno visible en tres meses. Si creces, suma dos o tres servicios complementarios y cóbralos cuando aporten valor real, como una consulta nutricional con cita. Si eres madura, profesionaliza la cartera con agenda online y programas de seguimiento: algunas farmacias maduras llegan a que el 18-22% de su facturación proceda de servicios (estimación sectorial). El error más común es lanzar tres servicios a la vez sin haber consolidado ninguno, así que ninguno llega a tener suficiente volumen para ser rentable.</p>
<p><strong>Paso 5. Sistematización</strong></p>
<p>Es convertir el crecimiento en un proceso planificado, no en un golpe de suerte puntual. Si estás estancada, empieza por planificar tus cuatro campañas grandes del año (alergias, solares, vuelta al cole, Navidad) con al menos 60 días de antelación: la inversión de tiempo es mínima y el retorno en categorías estacionales puede rondar el 25-35% (estimación sectorial). Si creces, amplía a un calendario de doce campañas y empieza a medir resultados por campaña, porque sin medición no hay sistema real. Si eres madura, delega la ejecución en tu equipo y reserva tu tiempo para marcar el rumbo. El error de siempre es dejar la planificación para los últimos quince días antes de cada campaña, que es justo lo que impide que se convierta en proceso.</p>
<p>La regla que sostiene todo el método es esta: una palanca activa por trimestre, no las cinco a la vez. Cuatro transformaciones reales al año valen mucho más que cinco intentos simultáneos que se quedan a medias.</p>
<h3>Errores frecuentes</h3>
<ul>
<li><strong>Activar las cinco palancas el mismo trimestre.</strong> Corrección: elige una, la que coincida con tu momento, y no toques las demás hasta que esta produzca resultado medible.</li>
<li><strong>Elegir la palanca que más apetece en vez de la que toca.</strong> Corrección: mira primero en qué momento estás (estancada, creciendo, madura) y deja que ese diagnóstico decida, no tu gusto personal.</li>
<li><strong>Copiar la estrategia de una farmacia madura sin tener lo básico resuelto.</strong> Corrección: si aún no tienes la ficha de Google completa, no tiene sentido invertir tiempo en alianzas sanitarias todavía.</li>
<li><strong>No anotar nada durante el trimestre.</strong> Corrección: fija desde el primer día un único número que vayas a mirar cada semana, aunque sea sencillo (visitas nuevas, ticket medio de una categoría, reseñas recibidas).</li>
</ul>
<h3>Hazlo hoy (10 minutos)</h3>
<p>Responde con sinceridad a estas cinco preguntas: ¿sabes cuánto facturó tu farmacia el mismo mes del año pasado sin abrir el ordenador? ¿tienes una campaña planificada con al menos 60 días de antelación? ¿tu farmacia funcionaría dos semanas sin ti exactamente igual que contigo? ¿conoces el ticket medio de cada categoría que vendes? ¿has captado al menos 30 clientes nuevos en los últimos seis meses?</p>
<p>Cuenta cuántos "no" tienes. Más de tres "no": estás estancada. Uno o dos: estás creciendo. Cinco "sí": eres madura. Con ese momento ya identificado, repasa las cinco palancas del método y marca la que reconozcas con más claridad en tu día a día: esa es la tuya para este trimestre. Escribe hoy mismo, en un papel o en el móvil, el nombre de la palanca elegida y la fecha en la que termina el trimestre. Solo una. La tuya.</p>
<h3>Cómo saber que funciona</h3>
<p>A los 30 días de haber elegido tu palanca, comprueba tres señales. Primera: puedes explicar en una sola frase qué has cambiado y por qué, sin dar rodeos ni justificaciones. Segunda: tienes al menos un número que puedes comparar entre el mes en el que empezaste y el mes anterior, aunque el cambio sea pequeño (una reseña más al día, un cliente nuevo más a la semana, un ticket medio que sube unos céntimos). Tercera: tu equipo sabe cuál es la prioridad del trimestre sin que tengas que repetírselo cada mañana. Si las tres son ciertas, la palanca está funcionando y merece los dos meses que le quedan de trimestre. Si ninguna lo es, revisa si de verdad elegiste la palanca que tocaba o la que te apetecía.</p>
<h3>Para seguir</h3>
<p>Esta píldora tiene tres descargables asociados: la «Guía: diagnóstico de las 5 palancas» (PDF), el «Autodiagnóstico de las 5 palancas» (Excel) y el «Dashboard del titular: las 5 palancas» (Excel), pensado para hacer seguimiento mensual durante todo el trimestre. Los tienes justo debajo, en "Recursos descargables".</p>
$c$, $r$[{"title": "Guía: diagnóstico de las 5 palancas", "url": "/recursos/impulso-diagnostico-5-palancas-guia.pdf", "type": "pdf", "resource_id": "1a25c26f-f731-4d30-8c10-e217c053be37"}, {"title": "Autodiagnóstico de las 5 palancas (Excel)", "url": "/recursos/impulso-diagnostico-5-palancas.xlsx", "type": "xls", "resource_id": "522c24a9-8734-4c92-80f8-2c476d39fa37"}, {"title": "Dashboard del titular: las 5 palancas", "url": "/recursos/impulso-dashboard-titular-5-palancas.xlsx", "type": "xls", "resource_id": "0b6fadd3-6661-4711-bd49-8483fd99af65"}]$r$::jsonb)
)
UPDATE public.courses c
SET course_modules = jsonb_set(
      jsonb_set(c.course_modules, '{0,content}', to_jsonb(m.content), true),
      '{0,downloadable_resources}', m.recursos, true),
    updated_at = now()
FROM mapeo m
WHERE c.slug = m.slug
  AND jsonb_array_length(c.course_modules) = 1
  AND c.course_modules->0->>'id' = m.mod_id;

-- Verificación: 8 filas, len_content > 9000, n_recursos 1 (3 en cinco-palancas), sin raya larga
SELECT slug,
       length(course_modules->0->>'content') AS len_content,
       jsonb_array_length(course_modules->0->'downloadable_resources') AS n_recursos,
       position('—' in course_modules->0->>'content') AS raya,
       updated_at
FROM public.courses
WHERE slug LIKE 'fp-pildora-%'
ORDER BY slug;

COMMIT;
