// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (o VITE_SUPABASE_URL) es obligatorio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS o SUPABASE_ANON_KEY es obligatorio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requiere un token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-courses.ts
var list_courses_default = defineTool({
  name: "list_courses",
  title: "Listar cursos",
  description: "Lista los cursos de formaci\xF3n publicados en el portal farmapro, con filtro opcional por categor\xEDa o b\xFAsqueda de texto en el t\xEDtulo.",
  inputSchema: {
    search: z.string().trim().max(100).optional().describe("Texto a buscar en el t\xEDtulo del curso."),
    category: z.string().trim().max(50).optional().describe("Categor\xEDa del curso (por ejemplo: ventas, marketing, gestion)."),
    limit: z.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de cursos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("courses").select("id, slug, title, description, category, difficulty, duration_hours, is_premium, rating, total_lessons").eq("is_published", true).order("order_index", { ascending: true }).limit(limit ?? 20);
    if (category) query = query.eq("category", category.replace(/[,()]/g, ""));
    if (search) query = query.ilike("title", `%${search.replace(/[%,()]/g, "")}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-resources.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_resources_default = defineTool2({
  name: "list_resources",
  title: "Listar recursos",
  description: "Lista los recursos descargables publicados (gu\xEDas, checklists, plantillas) del portal farmapro, con b\xFAsqueda opcional.",
  inputSchema: {
    search: z2.string().trim().max(100).optional().describe("Texto a buscar en el t\xEDtulo del recurso."),
    category: z2.string().trim().max(50).optional().describe("Categor\xEDa del recurso."),
    limit: z2.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de recursos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("resources").select("id, slug, title, description, category, type, format, is_premium, downloads_count").eq("is_published", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category.replace(/[,()]/g, ""));
    if (search) query = query.ilike("title", `%${search.replace(/[%,()]/g, "")}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { resources: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_events_default = defineTool3({
  name: "list_events",
  title: "Listar eventos",
  description: "Lista los pr\xF3ximos eventos publicados del portal farmapro (formaciones en directo, masterclasses, encuentros).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("N\xFAmero m\xE1ximo de eventos a devolver."),
    include_past: z3.boolean().default(false).describe("Incluir tambi\xE9n los eventos ya celebrados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, include_past }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("events").select("id, title, description, event_type, start_date, end_date, is_online, location, is_premium, registration_url").eq("is_published", true).order("start_date", { ascending: true }).limit(limit ?? 10);
    if (!include_past) query = query.gte("start_date", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-forum-threads.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_forum_threads_default = defineTool4({
  name: "list_forum_threads",
  title: "Listar hilos de la comunidad",
  description: "Lista los hilos m\xE1s recientes del foro de la comunidad farmapro, con b\xFAsqueda opcional en el t\xEDtulo.",
  inputSchema: {
    search: z4.string().trim().max(100).optional().describe("Texto a buscar en el t\xEDtulo del hilo."),
    limit: z4.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de hilos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("forum_threads").select("id, title, content, author_display_name, category_id, replies_count, views_count, is_pinned, created_at, last_reply_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search.replace(/[%,()]/g, "")}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { threads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-progress.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var my_progress_default = defineTool5({
  name: "my_progress",
  title: "Mi progreso",
  description: "Devuelve el progreso del usuario conectado en el portal farmapro: puntos, nivel, racha e insignias conseguidas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: profileError }, { data: badges, error: badgesError }] = await Promise.all([
      supabase.from("profiles").select("full_name, pharmacy_name, points, level, streak_days, last_activity_date").eq("id", userId).maybeSingle(),
      supabase.from("user_badges").select("earned_at, badges(name, description)").eq("user_id", userId).order("earned_at", { ascending: false })
    ]);
    const error = profileError ?? badgesError;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { profile: profile ?? null, badges: badges ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jeysistgdajopfruqpbc";
var mcp_default = defineMcp({
  name: "farmapro-cloud-connect",
  title: "Farmapro Cloud Connect",
  version: "0.1.0",
  instructions: "Herramientas del portal farmapro (formaci\xF3n y comunidad para farmacias). Permiten consultar cursos, recursos descargables, eventos, hilos del foro y el progreso del usuario conectado. Responde siempre en castellano y escribe 'farmapro' en min\xFAsculas.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, list_resources_default, list_events_default, list_forum_threads_default, my_progress_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
